### ISSUE TITLE
InternalServerError - Long running operation failed with status 'Failed' with KeyVault resource 

### ISSUE THREAD

**Issue by peter-bertok** [Azure/arm-template-whatif#261]
## Describe the noise

Microsoft.KeyVault/vaults

Tested 2021-10-01 and 2021-11-01-preview, but may also happen with older versions.

**Client (PowerShell, Azure CLI, or API)**

Azure Bicep deployed via New-AzResourceGroupDeployment

Bicep CLI version 0.5.6 (5f2f88f0f0)

Az module version 7.5.0

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

```bicep
resource keyVault 'Microsoft.KeyVault/vaults@2021-11-01-preview' = {
  name: Prefix
  location: Location
  properties: {
    enabledForDeployment: true
    enabledForTemplateDeployment: true
    enabledForDiskEncryption: true
    tenantId: subscription().tenantId
    accessPolicies: [] // Tried with and without this line present.
    sku: {
      name: 'standard'
      family: 'A'
    }
    enablePurgeProtection: true
    enableRbacAuthorization: true
    enableSoftDelete: true
  }
}
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

I'm deploying to an empty resource group. The -WhatIf command should show the new KeyVault being created. Note that I'm using Azure RBAC permissions, not the old Access Policies.

I tried with an without having "Key Vault Administrator" RBAC permissions on the Resource Group.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
New-AzResourceGroupDeployment: 
InternalServerError - Long running operation failed with status 'Failed'. Additional Info:'Encountered internal server error while processing the deployment what-if request. Diagnostic information: timestamp '20220427T035250Z', scope '###', tracking id 'dd85dd4a-aea3-4b04-84dd-73ee640672e6', request correlation id '41df34a0-3ba5-4aae-ac7a-c3f57583a495'.'
```

The full exception details are:

```
Message        : 
                 InternalServerError - Long running operation failed with status 'Failed'. Additional Info:'Encountered internal server error while processing the        
                 deployment what-if request. Diagnostic information: timestamp '20220427T035250Z', scope
                 '###', tracking id 'dd85dd4a-aea3-4b04-84dd-73ee640672e6', request      
                 correlation id '41df34a0-3ba5-4aae-ac7a-c3f57583a495'.'
Data           : {}
InnerException : Microsoft.Rest.Azure.CloudException:
                 InternalServerError - Long running operation failed with status 'Failed'. Additional Info:'Encountered internal server error while processing the        
                 deployment what-if request. Diagnostic information: timestamp '20220427T035250Z', scope
                 '###', request      
                 correlation id '41df34a0-3ba5-4aae-ac7a-c3f57583a495'.'
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.ExecuteDeploymentWhatIf(PSDeploymentWhatIfCmdletParameters 
                 parameters)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.CmdletBase.DeploymentWhatIfCmdlet.ExecuteWhatIf()
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.CmdletBase.DeploymentCreateCmdlet.OnProcessRecord()
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet.OnProcessRecord()
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
HelpLink       : 
Source         : Microsoft.Azure.PowerShell.Cmdlets.ResourceManager
HResult        : -2146233088
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException) 
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

**Comment by alex-frankel** [comment]
If you deploy *without* what-if, is the deployment successful?

**Comment by peter-bertok** [comment]
> If you deploy _without_ what-if, is the deployment successful?

Yes, it deploys just fine. It's only -WhatIf that causes the error.

**Comment by torreymicrosoft** [comment]
Thanks for your patience, and apologies for the long silence on this. It was recently picked up as an outstanding open issue for the ARM Deployments team to review.

I rebuilt the scenario as described and I cannot reproduce the InternalServerError.

Setup: a brand new, completely empty resource group (nothing was ever deployed into it), and a `Microsoft.KeyVault/vaults` template matching what you posted, with `enablePurgeProtection: true`, `enableRbacAuthorization: true`, `enableSoftDelete: true`, `softDeleteRetentionInDays: 90` and an empty `accessPolicies` array.

Run on Az.Accounts 5.5.0 and Az.Resources 10.0.0:

```
New-AzResourceGroupDeployment -ResourceGroupName <rg> -TemplateFile vault.json -WhatIf
```

At your original `2021-10-01`:

```
  + Microsoft.KeyVault/vaults/<name> [2021-10-01]

Resource changes: 1 to create.
```

Same clean `+ Create` at `2024-11-01`, and `Get-AzResourceGroupDeploymentWhatIfResult` against the same empty resource group also returned a single Create with no error.

To be sure the cmdlet was genuinely capable of failing rather than quietly passing, I pushed a deliberately policy blocked template through the same `-WhatIf` call against the same resource group. It threw, and notably in the same outer shape you saw: `Long running operation failed with status 'Failed'`. So that failure path is still very much live on this cmdlet, it just is not firing for this Key Vault template any more.

One thing I could not do is go back and look at what the service actually returned to you. The tracking and correlation IDs on this thread are from April 2022 and are well outside telemetry retention.

Worth keeping on the record: as you and Alex established at the time, the deployment itself succeeded and only `-WhatIf` failed. That isolation is the most useful detail here if it ever comes back.

Given I cannot reproduce it on current modules at either api-version, I am going to close this out. If a Key Vault what-if starts returning InternalServerError again, please reopen with the fresh tracking ID and the approximate time and region, and I will get it in front of the service team.
